### ISSUE TITLE
comentarios avance 3 y README

### ISSUE THREAD

**Issue by AliciaMstt** [mike9999999/ProyectoFinalBioinf2018-II#2]
OJO: no hay un readme en tu proyecto final, y esto vale el 15% del proyecto final. Recuerda:

1) Debe describir cuáles son los datos, en qué directorios están, y qué hace cada script y en qué orden deben correrse (o especificar qué hace el workflow maestro).

2) Debe ser en inglés

**Comment by mike9999999** [comment]
Vale, lo actualizaré.

**Comment by mike9999999** [comment]
Actalice el readme del avance 3. Tomando en cuenta unicamente lo que había hecho hasta ese momento. 

https://github.com/mike9999999/ProyectoFinalBioinf2018-II/blob/master/README%20AVANCE%203.md
